sonar.projectKey=Valeri123car_Projekt2026
sonar.organization=valeri123car
sonar.host.url=https://sonarcloud.io

sonar.sources=api/src,web/src,mobile/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.expo/**